parser: '@babel/eslint-parser'
parserOptions:
  requireConfigFile: false
  babelOptions:
    parserOpts:
      plugins:
        - jsx

plugins:
  - react
  - jest
  - testing-library
  - jest-dom

extends:
  - airbnb
  - "plugin:jest/recommended"
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"
  - "plugin:testing-library/react"
  - "plugin:jest-dom/recommended"

env:
  browser: true
  node: true
  jest: true
  # es2020: true

settings:
  jest:
    version: 29
#   import/resolver:
#     webpack:
#     node:
#     # webpack:
# #   react:
# #     version: "16.13"

rules:
  import/extensions: 0
  import/no-unresolved: 0
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - "**/__tests__/**"
        - "**/mocks/**"
        - "**/vite.config.*"
        - "**/setupTests.*"
  react/prop-types: 0
  no-console: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  max-len: 0
  testing-library/no-debug: 0
  testing-library/no-render-in-lifecycle: 0
  testing-library/no-debugging-utils: 0
